spring.application.name=Rentora

spring.datasource.url=jdbc:mysql://localhost:3306/coffee

spring.datasource.username=root
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect




spring.jpa.show-sql=true
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=create-drop

spring.web.error.include-message=always
spring.web.error.include-stacktrace=always

# Email Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=alwadaniabdulelah@gmail.com
spring.mail.password=fhheneqdjyksumez
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true